### ISSUE TITLE
`stty size` in MacRuby

### ISSUE THREAD

**Issue by sbai** [davetron5000/gli#132]
When using macruby-0.12, if I follow the instructions in the wiki:

```
> gli init todo list add complete
```

I get this result:

```
error: Unknown command 'complete'

stty: stdin isn't a terminal
/Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help_modules/text_wrapper.rb:30:in `block': comparison of Fixnum with nil failed (ArgumentError)
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help_modules/text_wrapper.rb:29:in `block'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help_modules/text_wrapper.rb:21:in `wrap'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help_modules/list_formatter.rb:17:in `block'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help_modules/list_formatter.rb:16:in `output'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help_modules/global_help_format.rb:27:in `format'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help.rb:76:in `show_help'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/commands/help.rb:60:in `block'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/command_support.rb:136:in `execute'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/app_support.rb:194:in `handle_exception'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/lib/gli/app_support.rb:73:in `run'
    from /Users/sbai/.rvm/gems/macruby-0.12/gems/gli-2.5.5/bin/gli:59:in `<main>'
    from /Users/sbai/.rvm/gems/macruby-0.12/bin/gli:19:in `<main>'
```

The problem seems to be this line in the Terminal class: 

```
lambda { run_command('stty size').scan(/\d+/).map { |size_element| size_element.to_i }.reverse }
```

The call to `run_command('stty size')` would evaluate to ``stty size``. If I paste that into macirb, I get the `stty: stdin isn't a terminal` portion of the error message above.

Not sure why the backticks method for calling stty fails in MacRuby. For what it's worth, `system('stty size')` gives

```
48 96
=> true
```

in MacRuby, so that could work as an alternative.

**Comment by davetron5000** [comment]
MacRuby is ancient and seems abandoned?  Closing due to that.  ALso it seems to support 1.9 which is an old version of Ruby that GLI no longer official supports.
