### ISSUE TITLE
in `find_command': Unknown command 'rdoc' (GLI::UnknownCommand)

### ISSUE THREAD

**Issue by mrjcleaver** [davetron5000/gli#204]
```
martincleaver@martincaversmbp.home:~/SoftwareDevelopment/proxmox-setup 18:40:17 817$ bundle exec bin/proxmox-setup rdoc
error: Unknown command 'rdoc'

NAME
    proxmox-setup - Setup Proxmox in various interesting ways, in Virtualbox etc.

SYNOPSIS
<...>
/Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/gli-2.12.2/lib/gli/command_finder.rb:26:in `find_command': Unknown command 'rdoc' (GLI::UnknownCommand)
    from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/gli-2.12.2/lib/gli/gli_option_parser.rb:42:in `parse!'
    from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/gli-2.12.2/lib/gli/gli_option_parser.rb:20:in `block in parse_options'
    from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/gli-2.12.2/lib/gli/gli_option_parser.rb:18:in `tap'
    from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/gli-2.12.2/lib/gli/gli_option_parser.rb:18:in `parse_options'
    from /Volumes/Storage/martincleaver/.chefdk/gem/ruby/2.1.0/gems/gli-2.12.2/lib/gli/app_support.rb:75:in `run'
    from bin/proxmox-setup:174:in `<main>'
```

Yet:

```
6$ rdoc
Parsing sources...
100% [33/33]  test/test_helper.rb                                               

Generating Darkfish format into /Volumes/Storage/martincleaver/SoftwareDevelopment/proxmox-setup/doc...

  Files:      33

  Classes:     2 ( 1 undocumented)
  Modules:     2 ( 2 undocumented)
  Constants:   2 ( 2 undocumented)
  Attributes:  0 ( 0 undocumented)
  Methods:    31 (24 undocumented)

  Total:      37 (29 undocumented)
   21.62% documented

  Elapsed: 1.2s
```

Code is here: https://github.com/mrjcleaver/proxmox-setup

Could equally be something about my chef+rbenv environment.

Thanks, Martin.

**Comment by rkachowski** [comment]
I hit this same issue, I was also under the impression that my readme file would be generated by gli.

>Generate this with
    proxmox-setup rdoc
After you have described your command line interface

- sets unclear expectations, no? if calling `rdoc` is the same as calling `foobar`, then why is the user instructed to do so?

**Comment by davetron5000** [comment]
Ah, seems like the issue is here: https://github.com/davetron5000/gli/blob/d76eac94de48b3837ac878747d5fade3f2be5a2e/lib/gli/commands/scaffold.rb#L47  It's telling you to use the old `rdoc` command and not `_doc`.
