### ISSUE TITLE
Test Suite is broken?

### ISSUE THREAD

**Issue by mrjcleaver** [davetron5000/gli#207]
I was just about to start making test cases. I haven't changed any of the template test code.
The base skeleton does not work for me.

```
6$ rake test
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /opt/chefdk/embedded/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  /Volumes/Storage/martincleaver/SoftwareDevelopment/proxmox-setup/test/test_helper.rb:1:in `<top (required)>'
  /Volumes/Storage/martincleaver/SoftwareDevelopment/proxmox-setup/test/default_test.rb:1:in `<top (required)>'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `select'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /opt/chefdk/embedded/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/opt/chefdk/embedded/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
    from /opt/chefdk/embedded/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Volumes/Storage/martincleaver/SoftwareDevelopment/proxmox-setup/test/test_helper.rb:1:in `<top (required)>'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Volumes/Storage/martincleaver/SoftwareDevelopment/proxmox-setup/test/default_test.rb:1:in `<top (required)>'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `select'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib" "/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/default_test.rb" "test/find_pve_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

test_helper.rb

```
require 'test/unit'

# Add test libraries you want to use here, e.g. mocha

class Test::Unit::TestCase

  # Add global extensions to the test case class here

end
```

default_test.rb

```
require 'test_helper'

class DefaultTest < Test::Unit::TestCase

  def setup
  end

  def teardown
  end

  def test_the_truth
    assert true
  end
end
```

Could you please verify this is a problem? Else I suppose it's something about my environment.

References:
- http://makandracards.com/makandra/25381-removing-minitest-warnings-from-rails-4-projects
- http://stackoverflow.com/questions/17461245/what-does-this-minitestunittestcase-warning-mean

**Comment by mauromorales** [comment]
I'm getting the same issue when running out of the box. Digging around I found in the [minitest release notes](http://blog.zenspider.com/releases/2013/05/minitest-version-5-0-0-has-been-released.html) that  **MiniTest::Unit::TestCase has been renamed to to Minitest::Test** in version 5

I did the following changes and it seems to work fine.

Inside `test/test_helper.rb` 

```ruby
# class Test::Unit::TestCase
class Minitest::Test
```

and `test/default_test.rb`

```ruby
# class DefaultTest < Test::Unit::TestCase
class DefaultTest < Minitest::Test
```

@davetron5000 I forked and did the changes in the scaffolding which seems to make it work but my tests are also having the same issues and I'm still trying to find out why. Once I do I'll submit a PR but thought about leaving this info here in case someone else has this problem.

**Comment by davetron5000** [comment]
Weird.  Please let me know if you have a fix.  I guess we can always do some sort of `Test::Unit::TestCase = Mintest::Test unless defined? Test::Unit::TestCase` shenanigans if we have to…

**Comment by louisrousseau** [comment]
Just ran `gli init test foo` trying to get this going... Took a few changes:

- Had to lock `aruba` to 0.8.1 in test.gemspec because using their latest 0.14.1 `cucumber` didn't work.
- Added `gem 'minitest'` in Gemspec
- Made changes as explained above by @mauromorales with the addition of a `require 'minitest/autorun'` line in test_helper.rb

I can now run `cucumber` and `rake test` successfully.

**Comment by davetron5000** [comment]
The test suite and the scaffold'ed one both use minitest explicitly and should be better.
